import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./component/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PhotoFeed",
  description: "Generated by PhotoFeed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`ms-5 mr-5 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar></NavBar>
        {children}
         <div id="modal-root-content"/>
      </body>
    </html>
  );
}
